[package]
name          = "rosu"
version       = "0.2.0"
authors       = ["MaxOhn <ohn.m@hotmail.de>"]
edition       = "2018"
description   = "A wrapper for the osu! API."
license       = "MIT"
readme        = "Readme.md"
keywords      = ["osu", "api", "wrapper"]
repository    = "https://github.com/MaxOhn/rosu"
documentation = "https://docs.rs/rosu/"

[dependencies]
bitflags     = "1.2"
chrono       = "0.4"
governor     = "0.2"
log          = "0.4"
serde        = "1.0"
serde_derive = "1.0"
serde_json   = "1.0"

[dependencies.futures]
version          = "0.3"
default-features = false

[dependencies.reqwest]
version          = "0.10"
default-features = false
features         = ["rustls-tls"]

[dev-dependencies]
env_logger = "0.7"
kankyo     = "0.3"
tokio      = { version = "0.2", features = ["rt-core", "macros"] }
