[package]
name = "rosu"
version = "0.1.0"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
edition = "2018"
description = "A wrapper for the osu! API."
license = "MIT"
readme = "Readme.md"
keywords = ["osu", "api", "wrapper"]
repository = "https://github.com/MaxOhn/rosu"
documentation = "https://docs.rs/rosu/"

[dependencies]
chrono = "0.4"
itertools = "0.8.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4.8"
futures = { version = "0.3.1", features = ["compat"] }
hyper = "0.13.1"
hyper-tls = "0.4.1"

[dev-dependencies]
env_logger = "0.7.1"
kankyo = "0.2"
tokio = "0.2.9"
