[package]
name = "example_usage"
version = "0.1.0"
authors = ["my name <my@email.address>"]
edition = "2018"

[dependencies]
rosu = "0.1.0"
tokio = { version = "0.2.9", features = ["full"] }
chrono = "0.4"
